#ifndef CONST_H
#define CONST_H

#define NOM_DU_FICHIER "test.txt"
#define NOMBRE_MAX_DE_BOITE_DE_DIALOGUE 999
#define NOMBRE_MAX_DE_CARACTERE_PAR_BOITE_DE_DIALOGUE 999
#define NOMBRE_MAX_DE_REPONSE_POSSIBLE 9
#define NOMBRE_MAX_DE_CARACTERE_PAR_REPONSE 999

#endif
